Table "_sqlx_migrations" {
  "version" int8 [pk, not null]
  "description" text [not null]
  "installed_on" timestamptz [not null, default: `now()`]
  "success" bool [not null]
  "checksum" bytea [not null]
  "execution_time" int8 [not null]
}

Table "account" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "email" text [not null]
  "name" text [not null]
  "avatar_url" text
  "description" text
  "verified" bool [not null, default: false]
  "enabled" bool [not null, default: false]
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]
}

Table "workspace" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "name" text [unique, not null]
  "slug" text [unique, not null]
  "description" text
  "config" jsonb [not null, default: `{}`]
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    slug [type: btree, name: "idx_workspace_slug"]
  }
}

Table "project" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "workspace_id" uuid [not null]
  "name" text [not null]
  "code" text
  "description" text
  "config" jsonb [not null, default: `{}`]
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    (workspace_id, name) [type: btree, name: "project_workspace_name_key"]
  }
}

Table "credential" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "account_id" uuid [not null]
  "workspace_id" uuid [unique, not null]
  "kind" text [not null]
  "provider" text
  "provider_id" text
  "email" text
  "secret" text
  "status" text [not null, default: 'active']
  "last_used_at" timestamptz
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    (workspace_id, provider, provider_id) [type: btree, name: "cred_oauth_unique_ns"]
    (workspace_id, provider, provider_id) [type: btree, name: "cred_oauth_lookup_idx"]
    (workspace_id, `lower(email)`) [type: btree, name: "cred_password_lookup_idx"]
  }
}

Table "role" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "workspace_id" uuid [not null]
  "name" text [not null]
  "description" text
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    (workspace_id, name) [type: btree, name: "role_workspace_name_key"]
  }
}

Table "permission" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "workspace_id" uuid [not null]
  "name" text [not null]
  "code" text
  "description" text
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    (workspace_id, name) [type: btree, name: "permission_workspace_name_key"]
  }
}

Table "role_permission" {
  "role_id" uuid [not null]
  "permission_id" uuid [not null]

  Indexes {
    (role_id, permission_id) [type: btree, name: "role_permission_pkey"]
    permission_id [type: btree, name: "rp_permission_idx"]
    role_id [type: btree, name: "rp_role_idx"]
  }
}

Table "membership" {
  "id" uuid [pk, not null, default: `gen_random_uuid()`]
  "account_id" uuid [not null]
  "workspace_id" uuid [not null]
  "scope" text [not null]
  "project_id" uuid
  "status" text [not null, default: 'active']
  "tags" "text[]" [not null, default: 'ARRAY[text[]']
  "meta" jsonb [not null, default: `{}`]
  "created_by" uuid [not null]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_by" uuid
  "updated_at" timestamptz
  "audit" jsonb [not null, default: `{}`]

  Indexes {
    (account_id, workspace_id) [type: btree, name: "membership_ns_unique"]
    (account_id, project_id) [type: btree, name: "membership_proj_unique"]
    (workspace_id, account_id) [type: btree, name: "membership_by_ns"]
    (project_id, account_id) [type: btree, name: "membership_by_proj"]
  }
}

Table "membership_role" {
  "membership_id" uuid [not null]
  "role_id" uuid [not null]

  Indexes {
    (membership_id, role_id) [type: btree, name: "membership_role_pkey"]
    membership_id [type: btree, name: "mr_membership_idx"]
    role_id [type: btree, name: "mr_role_idx"]
  }
}

Ref "cred_account_fk":"account"."id" < "credential"."account_id" [update: cascade, delete: cascade]

Ref "cred_workspace_fk":"workspace"."id" < "credential"."workspace_id" [update: cascade, delete: cascade]

Ref "mem_account_fk":"account"."id" < "membership"."account_id" [update: cascade, delete: cascade]

Ref "mem_workspace_fk":"workspace"."id" < "membership"."workspace_id" [update: cascade, delete: cascade]

Ref "mem_project_fk":"project"."id" < "membership"."project_id" [update: cascade, delete: cascade]

Ref "mr_membership_fk":"membership"."id" < "membership_role"."membership_id" [update: cascade, delete: cascade]

Ref "mr_role_fk":"role"."id" < "membership_role"."role_id" [update: cascade, delete: restrict]

Ref "perm_workspace_fk":"workspace"."id" < "permission"."workspace_id" [update: cascade, delete: cascade]

Ref "project_workspace_id_fkey":"workspace"."id" < "project"."workspace_id" [update: cascade, delete: cascade]

Ref "role_workspace_fk":"workspace"."id" < "role"."workspace_id" [update: cascade, delete: cascade]

Ref "rp_permission_fk":"permission"."id" < "role_permission"."permission_id" [update: cascade, delete: restrict]

Ref "rp_role_fk":"role"."id" < "role_permission"."role_id" [update: cascade, delete: cascade]
